export const GET_USER_REQUEST = 'GET_USERS_INIT';
export const GET_USER_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_FAILURE = 'GET_USERS_ERROR';

export const SET_FAVORITE_EPISODE_INIT = 'SET_FAVORITE_EPISODE_INIT';
export const SET_FAVORITE_EPISODE_SUCCESS = 'SET_FAVORITE_EPISODE_SUCCESS';
export const SET_FAVORITE_EPISODE_ERROR = 'SET_FAVORITE_EPISODE_ERROR';

export const REMOVE_FAVORITE_EPISODE_INIT = 'REMOVE_FAVORITE_EPISODE_INIT';
export const REMOVE_FAVORITE_EPISODE_SUCCESS = 'REMOVE_FAVORITE_EPISODE_SUCCESS';
export const REMOVE_FAVORITE_EPISODE_ERROR = 'REMOVE_FAVORITE_EPISODE_ERROR';


export const SET_FAVORITE_CHARACTER_INIT = 'SET_FAVORITE_CHARACTERS_INIT';
export const SET_FAVORITE_CHARACTER_SUCCESS = 'SET_FAVORITE_CHARACTERS_SUCCESS';
export const SET_FAVORITE_CHARACTER_ERROR = 'SET_FAVORITE_CHARACTERS_ERROR';

export const REMOVE_FAVORITE_CHARACTER_INIT = 'REMOVE_FAVORITE_CHARACTERS_INIT';
export const REMOVE_FAVORITE_CHARACTER_SUCCESS = 'REMOVE_FAVORITE_CHARACTERS_SUCCESS';
export const REMOVE_FAVORITE_CHARACTER_ERROR = 'REMOVE_FAVORITE_CHARACTERS_ERROR';



export const GETALL_REQUEST = 'USERS_GETALL_REQUEST';
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS';
export const GETALL_FAILURE = 'USERS_GETALL_FAILURE';
