export const GET_CHARACTERS_INIT = 'GET_CHARACTERS_INIT';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';


// export const GET_EPISODE_INIT = 'GET_EPISODE_INIT';
// export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
// export const GET_EPISODE_ERROR = 'GET_EPISODE_ERROR';
