export const GET_EPISODES_INIT = 'GET_EPISODES_INIT';
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_ERROR = 'GET_EPISODES_ERROR';


// export const GET_EPISODE_INIT = 'GET_EPISODE_INIT';
// export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
// export const GET_EPISODE_ERROR = 'GET_EPISODE_ERROR';
